// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jywumogugcfytjtsnjrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5d3Vtb2d1Z2NmeXRqdHNuanJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNDE4MTgsImV4cCI6MjA2NzcxNzgxOH0.GevJlXX5ExUkaDUH0uMhtk2Xsj_jzLtbqAvwam0qRCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});